### ISSUE TITLE
Compilation instructions?

### ISSUE THREAD

**Issue by Efreak** [kapolos/armhf-x2go#1]
Some information on how you got these to compile would me _much_ appreciated. Also, you might consider hacking a repository together via GitHub Pages so users could just add a line and apt-get install.

**Comment by kapolos** [comment]
Tbh, I don't remember much as the idea was to do it once and have the binaries for future use, so I didn't keep notes. I do have the build environment I used saved as an image though ([here](https://hub.docker.com/r/kapolos/armhf-x2go-build-environment/)), so I suppose that will take care of most of the dependency hunting.

I am not using armhf much any more, but if I get time during the weekend I'll try to figure out how to  re-compile (scrolling lines in the terminal are such fun :dancer:) and update the issue.

I wasn't aware about GitHub Pages as a repo directly, thank you (another thing for the backlog :laughing: ).

**Comment by kapolos** [comment]
Closing as I am not using armhf any longer.
